version: '3'

services:
  react-app:
    build:
      context: ./app/
      dockerfile: dockerfile
    ports:
      - "8085:8085"
    depends_on:
      - node
    restart: always
    
  node:
    build:
      context: ./server/
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    restart: always
   