# Use the official Node.js base image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose a port where your backend server will run
EXPOSE 8000

# Start the backend server when the container starts

CMD ["npm", "run", "start"] 
