#FROM node:lts-alpine AS BUILD

#WORKDIR /home/node/app

#COPY package*.json ./

#RUN npm install 

#COPY . .

#RUN npm run build




FROM node:lts-alpine AS PROD

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

#COPY --from=BUILD /home/node/app/dist ./

RUN npm run build

EXPOSE 8000

CMD ["npm", "run", "start"] 
